### ISSUE TITLE
User details

### ISSUE THREAD

**Issue by valdelaseras** [valdelaseras/pleagan#79]
We don't have anywhere for the user to state which country they live in, I think we should do this at sign up, explain why we want to know and give the user an option to hide their country from the pleas and supports ( but that we will use the info in our stats )

**Comment by valdelaseras** [comment]
- I added a country select in registration
- Set a checkbox in /settings for the user to hide their country from public. The data will still be used anonymously in stats/charts
@daftfox  please update backend once I've merged feature/stuff

**Comment by daftfox** [comment]
user is able to change their country of residence as well as hide it from other users.
