### ISSUE TITLE
Tab flow

### ISSUE THREAD

**Issue by valdelaseras** [valdelaseras/pleagan#80]
Tab index on tab elements

**Comment by valdelaseras** [comment]
hmmm, buttons on home page don't change state on tab. It doesn't seem to tab there at all ( even with tabindex attr )

**Comment by valdelaseras** [comment]
Tabbing through navigation works but there is no visual feedback

Nav trigger does not seem tab-able however

**Comment by valdelaseras** [comment]
Tabbing through all pleas goed top down from left to right and I can only tab from card to card, not to the support plea btn

**Comment by daftfox** [comment]
The focus style of ALL elements was disabled in the _reset.scss stylesheet. I have taken this out and applied the correct colors to focused elements.
