### ISSUE TITLE
Initiate plea duplication check 

### ISSUE THREAD

**Issue by valdelaseras** [valdelaseras/pleagan#85]
<img width="780" alt="Screenshot 2021-03-13 at 21 39 47" src="https://user-images.githubusercontent.com/40611703/111024633-b557ba00-8444-11eb-9114-243125906c99.png">

in this scenario we should display a message in the card like 'you're good'. I think we actually had this before? What happened?

**Comment by daftfox** [comment]
![image](https://user-images.githubusercontent.com/6339905/114261579-6a26cc00-9a2f-11eb-85c1-d02aa3d5f2ee.png)
It seems that this has already been fixed in an earlier commit. Closing for now.
