### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by valdelaseras** [valdelaseras/pleagan#87]
should trigger on typing ( now only triggers on tab or enter ) and shows a plea like so when found:

<img width="521" alt="Screenshot 2021-03-13 at 22 05 48" src="https://user-images.githubusercontent.com/40611703/111025330-54ca7c00-8448-11eb-918a-44dbfbe0e7d3.png">

note: 0 current supporter

**Comment by valdelaseras** [comment]
Progress bar is naturally also not working ( since we've got no supporters )

**Comment by daftfox** [comment]
Issue has been fixed. Pull pleagan-service from master.
