### ISSUE TITLE
Refreshing problems

### ISSUE THREAD

**Issue by valdelaseras** [valdelaseras/pleagan#94]
Log in > go to all pleas > refresh page, get blank page. 

<img width="774" alt="Screenshot 2021-03-13 at 23 50 36" src="https://user-images.githubusercontent.com/40611703/111027726-efca5280-8456-11eb-8814-6d902308c746.png">

**Comment by valdelaseras** [comment]
Also happens if you just enter http://localhost:4200/plea/all or any other url

**Comment by daftfox** [comment]
Fix for this issue has been pushed to dev.
